"""Add execution_mode to DecisionFunnelLog

Revision ID: 12845e0151a9
Revises: f47295cae843
Create Date: 2026-08-02 15:27:50.037533+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12845e0151a9'
down_revision: Union[str, None] = 'f47295cae843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_history_legacy')
    op.drop_table('crypto_candles_backup')
    with op.batch_alter_table('decision_funnel_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_mode', sa.String(length=16), nullable=True))
        batch_op.alter_column('trading_mode',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               nullable=True)

    with op.batch_alter_table('execution_attempts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_execution_attempt_number', ['request_id', 'attempt_no'])
        batch_op.create_unique_constraint('uq_execution_provider_order', ['gateway', 'provider_order_id'])

    with op.batch_alter_table('execution_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_requests_live_session'))
        batch_op.drop_index(batch_op.f('uq_live_request_source_paper'), postgresql_where="(((requested_mode)::text = 'LIVE'::text) AND ((intent)::text = 'OPEN'::text) AND (source_paper_request_id IS NOT NULL))")

    with op.batch_alter_table('exposure_reservations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'execution_requests', ['request_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'trade_history', ['trade_history_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('live_mirror_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_mirror_candidates_source_paper_request_id'))

    with op.batch_alter_table('live_trading_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_live_session_single_controllable'), postgresql_where="((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'READY'::character varying, 'ACTIVE'::character varying])::text[]))")

    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_history_live_session'))
        batch_op.drop_index(batch_op.f('uq_live_trade_source_paper'), postgresql_where="(((mode)::text = 'LIVE'::text) AND (source_paper_trade_id IS NOT NULL))")
        batch_op.drop_constraint(batch_op.f('trade_history_source_paper_trade_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trade_history', ['source_paper_trade_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trade_history_source_paper_trade_id_fkey'), 'trade_history', ['source_paper_trade_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('uq_live_trade_source_paper'), ['source_paper_trade_id'], unique=True, postgresql_where="(((mode)::text = 'LIVE'::text) AND (source_paper_trade_id IS NOT NULL))")
        batch_op.create_index(batch_op.f('ix_trade_history_live_session'), ['live_session_id', 'position_status'], unique=False)

    with op.batch_alter_table('live_trading_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_live_session_single_controllable'), [sa.literal_column('(1)')], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'READY'::character varying, 'ACTIVE'::character varying])::text[]))")

    with op.batch_alter_table('live_mirror_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_mirror_candidates_source_paper_request_id'), ['source_paper_request_id'], unique=False)

    with op.batch_alter_table('exposure_reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('execution_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_live_request_source_paper'), ['source_paper_request_id'], unique=True, postgresql_where="(((requested_mode)::text = 'LIVE'::text) AND ((intent)::text = 'OPEN'::text) AND (source_paper_request_id IS NOT NULL))")
        batch_op.create_index(batch_op.f('ix_execution_requests_live_session'), ['live_session_id', 'created_at'], unique=False)

    with op.batch_alter_table('execution_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_execution_provider_order', type_='unique')
        batch_op.drop_constraint('uq_execution_attempt_number', type_='unique')

    with op.batch_alter_table('decision_funnel_log', schema=None) as batch_op:
        batch_op.alter_column('trading_mode',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('execution_mode')

    op.create_table('crypto_candles_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('interval', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('taker_buy_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=16), autoincrement=False, nullable=True)
    )
    op.create_table('trade_history_legacy',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('market_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('asset', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('outcome_bought', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('amount_usdc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('executed_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('predicted_flip_prob', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('active_features', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('edge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('p_up', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('strike', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('stop_loss_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('stop_loss_hit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('stop_loss_sell_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('take_profit_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('take_profit_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('take_profit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('take_profit_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('take_profit_hit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('take_profit_sell_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lgbm_metadata', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config_snapshot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('position_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('exit_reason', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('exit_order_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('exit_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_sell_size', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True),
    sa.Column('take_profit_sell_size', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True),
    sa.Column('position_accounting_version', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('entry_filled_shares', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True),
    sa.Column('entry_cost_usdc', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True),
    sa.Column('remaining_shares', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True),
    sa.Column('realized_pnl_usdc', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=True),
    sa.Column('exit_attempt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('exit_claimed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_exit_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strategy_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('market_role', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('p_flip_effective', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('p_win_effective', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('position_version', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
