"""Add direction discount columns

Revision ID: 3c3c82ccf12b
Revises: merge_all_heads
Create Date: 2026-08-04 17:08:54.662112+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3c82ccf12b'
down_revision: Union[str, None] = 'merge_all_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_funnel_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_logreg_win', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('direction_discount_mult', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('combined_dir_discount_weight', sa.Float(), nullable=True))

    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_logreg_win', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('direction_discount_mult', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('combined_dir_discount_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.drop_column('combined_dir_discount_weight')
        batch_op.drop_column('direction_discount_mult')
        batch_op.drop_column('p_logreg_win')

    with op.batch_alter_table('decision_funnel_log', schema=None) as batch_op:
        batch_op.drop_column('combined_dir_discount_weight')
        batch_op.drop_column('direction_discount_mult')
        batch_op.drop_column('p_logreg_win')

    # ### end Alembic commands ###
