"""add trade_history and live_markets

Revision ID: 48db8ee4d282
Revises: 595163989ed2
Create Date: 2026-06-26 11:43:36.654972+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48db8ee4d282'
down_revision: Union[str, None] = '595163989ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_market_recorded', 'market_snapshots', ['market_id', 'recorded_at'])
    op.add_column('trade_history', sa.Column('mode', sa.String(length=16), nullable=False))
    op.add_column('trade_history', sa.Column('pnl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_history', 'pnl')
    op.drop_column('trade_history', 'mode')
    op.drop_constraint('uix_market_recorded', 'market_snapshots', type_='unique')
    # ### end Alembic commands ###
