"""add_index_trade_history_model_version

Revision ID: b258f4d83d08
Revises: 42a7b3c4d5e9
Create Date: 2026-07-21 04:13:39.975412+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b258f4d83d08'
down_revision: Union[str, None] = '42a7b3c4d5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_history', 'lgbm_metadata',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('idx_trade_history_model_version', 'trade_history', ['asset', 'model_version', 'status', 'created_at'], unique=False)
    op.drop_column('trade_history', 'take_profit_sell_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_history', sa.Column('take_profit_sell_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index('idx_trade_history_model_version', table_name='trade_history')
    op.alter_column('trade_history', 'lgbm_metadata',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
