"""add_stoploss_columns_to_trade_history

Revision ID: b34a6b9256f3
Revises: 5b1cefabc64a
Create Date: 2026-07-08 17:01:50.225798+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34a6b9256f3'
down_revision: Union[str, None] = '5b1cefabc64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_candle_symbol_interval_time'), table_name='crypto_candles')
    op.add_column('trade_history', sa.Column('market_end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trade_history', sa.Column('stop_loss_pct', sa.Float(), nullable=True))
    op.add_column('trade_history', sa.Column('stop_loss_price', sa.Float(), nullable=True))
    op.add_column('trade_history', sa.Column('stop_loss_status', sa.String(length=20), nullable=True))
    op.add_column('trade_history', sa.Column('stop_loss_hit_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trade_history', sa.Column('stop_loss_sell_price', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_trade_history_created_at'), table_name='trade_history')
    op.drop_index(op.f('idx_trade_history_status'), table_name='trade_history')
    op.drop_column('trade_history', 'kelly_multiplier')
    op.drop_column('trade_history', 'kelly_fraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_history', sa.Column('kelly_fraction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trade_history', sa.Column('kelly_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_trade_history_status'), 'trade_history', ['status'], unique=False)
    op.create_index(op.f('idx_trade_history_created_at'), 'trade_history', ['created_at'], unique=False)
    op.drop_column('trade_history', 'stop_loss_sell_price')
    op.drop_column('trade_history', 'stop_loss_hit_at')
    op.drop_column('trade_history', 'stop_loss_status')
    op.drop_column('trade_history', 'stop_loss_price')
    op.drop_column('trade_history', 'stop_loss_pct')
    op.drop_column('trade_history', 'market_end_time')
    op.create_index(op.f('ix_crypto_candle_symbol_interval_time'), 'crypto_candles', ['symbol', 'interval', sa.literal_column('open_time DESC')], unique=False)
    # ### end Alembic commands ###
