"""analytics_refactoring_p0_p12

Revision ID: f47295cae843
Revises: c1a2b3d4e5f6
Create Date: 2026-08-02 14:32:01.181957+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f47295cae843'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_funnel_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_model_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('primary_model_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirm_model_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('confirm_model_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proposed_action', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('proposed_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('proposed_amount_usdc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confirm_direction', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('confirm_passed', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_funnel_confirm_model_analytics', ['confirm_model_key', 'confirm_model_version', 'created_at'], unique=False)

    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('train_samples', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validation_samples', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('positive_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('precision_at_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recall_at_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f1_at_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('brier_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_window_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('training_window_end', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.create_index('idx_trade_confirm_model_analytics', ['mode', 'confirm_model_key', 'confirm_model_version', 'position_status', 'closed_at'], unique=False)
        batch_op.create_index('idx_trade_model_analytics', ['mode', 'model_key', 'model_version', 'position_status', 'closed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.drop_index('idx_trade_model_analytics')
        batch_op.drop_index('idx_trade_confirm_model_analytics')

    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.drop_column('training_window_end')
        batch_op.drop_column('training_window_start')
        batch_op.drop_column('brier_score')
        batch_op.drop_column('f1_at_threshold')
        batch_op.drop_column('recall_at_threshold')
        batch_op.drop_column('precision_at_threshold')
        batch_op.drop_column('positive_rate')
        batch_op.drop_column('validation_samples')
        batch_op.drop_column('train_samples')
        batch_op.drop_column('feature_importance')
        batch_op.drop_column('training_params')
        batch_op.drop_column('decision_threshold')

    with op.batch_alter_table('decision_funnel_log', schema=None) as batch_op:
        batch_op.drop_index('idx_funnel_confirm_model_analytics')
        batch_op.drop_column('confirm_passed')
        batch_op.drop_column('confirm_direction')
        batch_op.drop_column('proposed_amount_usdc')
        batch_op.drop_column('proposed_price')
        batch_op.drop_column('proposed_action')
        batch_op.drop_column('confirm_model_version')
        batch_op.drop_column('confirm_model_key')
        batch_op.drop_column('primary_model_version')
        batch_op.drop_column('primary_model_key')

    # ### end Alembic commands ###
