"""LLM Provider abstraction and structured hypothesis schemas for AI Lab Phase 10.

Integrates with OpenAI Responses API (store=False) and provides deterministic MockLLMProvider.
"""

from __future__ import annotations

import hashlib
import json
import time
from collections.abc import Mapping
from typing import Any, Protocol, runtime_checkable
from pydantic import BaseModel, Field, field_validator
import structlog

logger = structlog.get_logger("polyflip.ai_lab.llm")

ALLOWED_MODEL_FAMILIES = {"LOGREG", "LIGHTGBM", "LogisticRegression", "LightGBM"}
ALLOWED_FEATURE_SETS = {"FS_D0", "FS_D1", "FS_D2", "FS_D3", "FS_D4", "FS_D5", "DEFAULT"}
ALLOWED_MARKET_ROLES = {"FAVORITE", "OUTSIDER", "COMBINED", "DIRECTION_ONLY", "ALL"}
ALLOWED_ASSETS = {"BTC", "ETH", "SOL", "BTCUSDT", "ETHUSDT", "SOLUSDT"}


# ---------------------------------------------------------------------------
# Structured Output Schemas
# ---------------------------------------------------------------------------
class HypothesisProposal(BaseModel):
    """Structured hypothesis and experiment plan generated by the LLM."""

    hypothesis: str = Field(..., min_length=10, max_length=2000, description="Clear statement of market hypothesis")
    asset: str = Field(..., description="Target trading asset (e.g. BTC, ETH, SOL)")
    market_role: str = Field(default="ALL", description="Target market role: FAVORITE, OUTSIDER, COMBINED, ALL")
    model_family: str = Field(..., description="ML algorithm: LOGREG or LIGHTGBM")
    feature_set: str = Field(..., description="Feature pipeline identifier, e.g. FS_D0, FS_D1, FS_D2")
    parameter_changes: dict[str, Any] = Field(default_factory=dict, description="Hyperparameters for model training")
    strategy_parameter_changes: dict[str, Any] = Field(
        default_factory=dict, description="Strategy parameters, e.g. decision_threshold, min_edge"
    )
    expected_effect: dict[str, Any] = Field(
        default_factory=lambda: {"metric": "median_oot_pnl", "direction": "increase"},
        description="Expected quantitative improvement",
    )
    reasoning: list[str] = Field(default_factory=list, description="List of logical arguments supporting the hypothesis")
    risks: list[str] = Field(default_factory=list, description="Identified risks or selection bias concerns")
    test_plan: dict[str, Any] = Field(
        default_factory=lambda: {"oot_windows": 3, "min_markets": 50, "execution_mode": "PAPER_REALISTIC"},
        description="Evaluation protocol parameters",
    )

    @field_validator("asset")
    @classmethod
    def validate_asset(cls, v: str) -> str:
        clean = v.upper().replace("USDT", "")
        if clean not in {"BTC", "ETH", "SOL"}:
            raise ValueError(f"Unsupported asset: '{v}'. Must be one of BTC, ETH, SOL.")
        return clean + "USDT"

    @field_validator("model_family")
    @classmethod
    def validate_family(cls, v: str) -> str:
        if v not in ALLOWED_MODEL_FAMILIES:
            raise ValueError(f"Disallowed model family '{v}'. Must be in {ALLOWED_MODEL_FAMILIES}")
        if v.upper().startswith("LOG"):
            return "LogisticRegression"
        return "LightGBM"

    @field_validator("feature_set")
    @classmethod
    def validate_feature_set(cls, v: str) -> str:
        v_upper = v.upper()
        if not (v_upper.startswith("FS_") or v_upper in ALLOWED_FEATURE_SETS or v.isalnum() or "_" in v):
            raise ValueError(f"Invalid feature set name '{v}'.")
        return v_upper

    @field_validator("market_role")
    @classmethod
    def validate_role(cls, v: str) -> str:
        v_upper = v.upper()
        if v_upper not in ALLOWED_MARKET_ROLES:
            raise ValueError(f"Invalid market role '{v}'. Must be in {ALLOWED_MARKET_ROLES}")
        return v_upper


class AgentDecision(BaseModel):
    """Structured decision after analyzing experiment results."""

    action: str = Field(
        ...,
        description="Action to take: CONTINUE_RESEARCH, MUTATE_HYPOTHESIS, RECOMMEND_SHADOW, FINALIZE_NO_WINNER, APPLY_OVERLAY, REQUEST_LIVE_APPROVAL",
    )
    rationale: str = Field(..., min_length=10, description="Detailed explanation of the analytical reasoning")
    key_findings: list[str] = Field(default_factory=list, description="Key empirical observations from OOT metrics")
    recommended_config_id: int | None = Field(default=None, description="Winning experiment config id if eligible")
    proposed_overlay: dict[str, Any] | None = Field(
        default=None, description="Proposed temporary runtime settings overlay"
    )
    next_step_focus: str | None = Field(default=None, description="Focus area for the next iteration if continuing")

    @field_validator("action")
    @classmethod
    def validate_action(cls, v: str) -> str:
        allowed = {
            "CONTINUE_RESEARCH",
            "MUTATE_HYPOTHESIS",
            "RECOMMEND_SHADOW",
            "FINALIZE_NO_WINNER",
            "APPLY_OVERLAY",
            "REQUEST_LIVE_APPROVAL",
            "STOP_BUDGET_EXHAUSTED",
        }
        if v.upper() not in allowed:
            raise ValueError(f"Invalid agent action '{v}'. Must be one of {sorted(allowed)}")
        return v.upper()


class LLMUsageStats(BaseModel):
    """Token usage and cost tracking for LLM calls."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    estimated_cost_usd: float = 0.0
    latency_ms: int = 0
    provider: str = "openai"
    model: str = "gpt-4o"
    prompt_hash: str = ""
    response_hash: str = ""


# ---------------------------------------------------------------------------
# Context Dataclasses
# ---------------------------------------------------------------------------
class AgentContext(BaseModel):
    """Snapshot context provided to the LLM for hypothesis formation."""

    run_id: int
    asset: str
    autonomy_level: str
    budget_remaining_steps: int
    current_active_model: dict[str, Any] | None = None
    baseline_metrics: dict[str, Any] = Field(default_factory=dict)
    feature_sets_available: list[str] = Field(default_factory=lambda: ["FS_D0", "FS_D1", "FS_D2"])
    previous_hypotheses: list[dict[str, Any]] = Field(default_factory=list)
    failed_experiments: list[dict[str, Any]] = Field(default_factory=list)
    market_statistics: dict[str, Any] = Field(default_factory=dict)


class AnalysisContext(BaseModel):
    """Context provided to the LLM after experiment execution."""

    run_id: int
    hypothesis: HypothesisProposal
    config_id: int
    metrics: dict[str, Any]
    baseline_comparison: dict[str, Any]
    finalization_gate: dict[str, Any]
    iteration: int
    budget_remaining_steps: int


# ---------------------------------------------------------------------------
# LLM Provider Protocol & Implementations
# ---------------------------------------------------------------------------
@runtime_checkable
class LLMProvider(Protocol):
    """Protocol for LLM reasoning backends."""

    async def propose_hypothesis(
        self,
        context: AgentContext,
    ) -> tuple[HypothesisProposal, LLMUsageStats]:
        ...

    async def analyze_experiment(
        self,
        context: AnalysisContext,
    ) -> tuple[AgentDecision, LLMUsageStats]:
        ...

    async def summarize_step(
        self,
        step_name: str,
        details: Mapping[str, Any],
    ) -> tuple[str, LLMUsageStats]:
        ...


class MockLLMProvider:
    """Deterministic Mock LLM provider for unit tests and local offline development."""

    def __init__(self, model_name: str = "mock-gpt-5") -> None:
        self.model_name = model_name
        self.call_count = 0

    async def propose_hypothesis(
        self,
        context: AgentContext,
    ) -> tuple[HypothesisProposal, LLMUsageStats]:
        self.call_count += 1
        asset = context.asset or "BTCUSDT"
        clean_asset = asset.replace("USDT", "")

        # Alternate between LogReg and LightGBM across iterations
        family = "LogisticRegression" if (self.call_count % 2 == 1) else "LightGBM"
        feature_set = f"FS_D{self.call_count % 3}"

        proposal = HypothesisProposal(
            hypothesis=f"Iter {self.call_count}: Calibrated {family} on {feature_set} reduces outsider mispricing on {clean_asset}",
            asset=clean_asset,
            market_role="FAVORITE" if self.call_count % 2 == 1 else "OUTSIDER",
            model_family=family,
            feature_set=feature_set,
            parameter_changes={"C": 0.5, "max_iter": 200} if family == "LogisticRegression" else {"n_estimators": 50, "learning_rate": 0.05},
            strategy_parameter_changes={"decision_threshold": 0.58, "min_edge": 0.03},
            expected_effect={"metric": "median_oot_pnl", "direction": "increase", "target_gain": 0.05},
            reasoning=[
                f"Historical OOT evaluations indicate stability for {clean_asset} under {feature_set}",
                "Regularization dampens overconfidence in late-phase trading windows",
            ],
            risks=["Small sample size in extreme market volatility", "Slippage on execution"],
            test_plan={"oot_windows": 3, "min_markets": 50, "execution_mode": "PAPER_REALISTIC"},
        )
        stats = LLMUsageStats(
            prompt_tokens=250,
            completion_tokens=180,
            total_tokens=430,
            estimated_cost_usd=0.001,
            latency_ms=45,
            provider="mock",
            model=self.model_name,
            prompt_hash=hashlib.sha256(b"mock_prompt").hexdigest(),
            response_hash=hashlib.sha256(proposal.hypothesis.encode("utf-8")).hexdigest(),
        )
        return proposal, stats

    async def analyze_experiment(
        self,
        context: AnalysisContext,
    ) -> tuple[AgentDecision, LLMUsageStats]:
        self.call_count += 1
        gate_passed = context.finalization_gate.get("passed", False)
        median_pnl = context.metrics.get("median_pnl", 0.0)

        if gate_passed and median_pnl > 0:
            action = "RECOMMEND_SHADOW"
            rationale = f"Candidate {context.config_id} passed all strict finalization criteria with positive median PnL ({median_pnl:.4f} USDC)."
        elif context.budget_remaining_steps <= 1:
            action = "FINALIZE_NO_WINNER"
            rationale = f"Budget exhausted after {context.iteration} iterations. No candidate decisively beat baseline with gate clearance."
        else:
            action = "CONTINUE_RESEARCH"
            rationale = f"Experiment {context.config_id} showed promising direction (PnL: {median_pnl:.4f}), mutating regularization for next window."

        decision = AgentDecision(
            action=action,
            rationale=rationale,
            key_findings=[
                f"OOT Net PnL: {median_pnl:.4f} USDC across windows",
                f"Gate status: {'PASSED' if gate_passed else 'REJECTED'}",
            ],
            recommended_config_id=context.config_id if gate_passed else None,
            proposed_overlay={"MIN_EDGE": 0.035} if gate_passed else None,
            next_step_focus="Refine feature set to FS_D2 with tighter outlier clamping" if action == "CONTINUE_RESEARCH" else None,
        )
        stats = LLMUsageStats(
            prompt_tokens=320,
            completion_tokens=150,
            total_tokens=470,
            estimated_cost_usd=0.0012,
            latency_ms=50,
            provider="mock",
            model=self.model_name,
            prompt_hash=hashlib.sha256(b"mock_analysis_prompt").hexdigest(),
            response_hash=hashlib.sha256(decision.rationale.encode("utf-8")).hexdigest(),
        )
        return decision, stats

    async def summarize_step(
        self,
        step_name: str,
        details: Mapping[str, Any],
    ) -> tuple[str, LLMUsageStats]:
        summary_text = f"Step '{step_name}' completed with status: {details.get('status', 'SUCCESS')}. Details: {json.dumps(dict(details), default=str)[:200]}"
        stats = LLMUsageStats(
            prompt_tokens=100,
            completion_tokens=50,
            total_tokens=150,
            estimated_cost_usd=0.0003,
            latency_ms=20,
            provider="mock",
            model=self.model_name,
        )
        return summary_text, stats


class OpenAIResponsesProvider:
    """OpenAI Responses API provider with structured outputs and zero persistence."""

    def __init__(
        self,
        api_key: str,
        model_research: str = "gpt-4o",
        model_summary: str = "gpt-4o-mini",
        store: bool = False,
        timeout_seconds: float = 60.0,
    ) -> None:
        self.api_key = api_key
        self.model_research = model_research
        self.model_summary = model_summary
        self.store = store
        self.timeout_seconds = timeout_seconds

    def _compute_cost(self, prompt_tokens: int, completion_tokens: int, model: str) -> float:
        # Approximate pricing per 1M tokens
        if "mini" in model.lower():
            return (prompt_tokens * 0.15 + completion_tokens * 0.60) / 1_000_000.0
        return (prompt_tokens * 2.50 + completion_tokens * 10.00) / 1_000_000.0

    async def propose_hypothesis(
        self,
        context: AgentContext,
    ) -> tuple[HypothesisProposal, LLMUsageStats]:
        import httpx

        prompt_payload = {
            "instructions": (
                "You are an autonomous quant researcher for Polymarket crypto binary outcome markets. "
                "Formulate a testable ML hypothesis for model architecture, feature sets (FS_D0, FS_D1, FS_D2), "
                "and strategy decision thresholds. Never propose shell commands, external network calls, or direct LIVE trades."
            ),
            "context": context.model_dump(),
        }
        serialized_prompt = json.dumps(prompt_payload, sort_keys=True)
        prompt_hash = hashlib.sha256(serialized_prompt.encode("utf-8")).hexdigest()

        start_time = time.time()
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        request_body = {
            "model": self.model_research,
            "messages": [
                {
                    "role": "system",
                    "content": prompt_payload["instructions"],
                },
                {
                    "role": "user",
                    "content": f"Current market context and history:\n{json.dumps(context.model_dump(), indent=2)}",
                },
            ],
            "response_format": {
                "type": "json_object",
            },
            "store": self.store,
            "temperature": 0.7,
        }

        async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
            try:
                response = await client.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers=headers,
                    json=request_body,
                )
                response.raise_for_status()
                data = response.json()
            except Exception as exc:
                logger.error("openai_propose_hypothesis_failed", error=str(exc))
                raise

        latency_ms = int((time.time() - start_time) * 1000)
        raw_content = data["choices"][0]["message"]["content"]
        response_hash = hashlib.sha256(raw_content.encode("utf-8")).hexdigest()

        usage = data.get("usage", {})
        prompt_tokens = usage.get("prompt_tokens", 0)
        completion_tokens = usage.get("completion_tokens", 0)
        total_tokens = usage.get("total_tokens", prompt_tokens + completion_tokens)
        cost = self._compute_cost(prompt_tokens, completion_tokens, self.model_research)

        parsed_json = json.loads(raw_content)
        proposal = HypothesisProposal.model_validate(parsed_json)

        stats = LLMUsageStats(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
            estimated_cost_usd=cost,
            latency_ms=latency_ms,
            provider="openai",
            model=self.model_research,
            prompt_hash=prompt_hash,
            response_hash=response_hash,
        )
        return proposal, stats

    async def analyze_experiment(
        self,
        context: AnalysisContext,
    ) -> tuple[AgentDecision, LLMUsageStats]:
        import httpx

        prompt_payload = {
            "instructions": (
                "You are an analytical evaluator. Analyze out-of-time (OOT) Polymarket backtest metrics, "
                "compare against baseline, check strict finalization gate clearance, and decide the next experiment step."
            ),
            "context": context.model_dump(),
        }
        serialized_prompt = json.dumps(prompt_payload, sort_keys=True)
        prompt_hash = hashlib.sha256(serialized_prompt.encode("utf-8")).hexdigest()

        start_time = time.time()
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        request_body = {
            "model": self.model_research,
            "messages": [
                {
                    "role": "system",
                    "content": prompt_payload["instructions"],
                },
                {
                    "role": "user",
                    "content": f"Experiment results and evaluation data:\n{json.dumps(context.model_dump(), indent=2)}",
                },
            ],
            "response_format": {
                "type": "json_object",
            },
            "store": self.store,
            "temperature": 0.2,
        }

        async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
            try:
                response = await client.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers=headers,
                    json=request_body,
                )
                response.raise_for_status()
                data = response.json()
            except Exception as exc:
                logger.error("openai_analyze_experiment_failed", error=str(exc))
                raise

        latency_ms = int((time.time() - start_time) * 1000)
        raw_content = data["choices"][0]["message"]["content"]
        response_hash = hashlib.sha256(raw_content.encode("utf-8")).hexdigest()

        usage = data.get("usage", {})
        prompt_tokens = usage.get("prompt_tokens", 0)
        completion_tokens = usage.get("completion_tokens", 0)
        total_tokens = usage.get("total_tokens", prompt_tokens + completion_tokens)
        cost = self._compute_cost(prompt_tokens, completion_tokens, self.model_research)

        parsed_json = json.loads(raw_content)
        decision = AgentDecision.model_validate(parsed_json)

        stats = LLMUsageStats(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
            estimated_cost_usd=cost,
            latency_ms=latency_ms,
            provider="openai",
            model=self.model_research,
            prompt_hash=prompt_hash,
            response_hash=response_hash,
        )
        return decision, stats

    async def summarize_step(
        self,
        step_name: str,
        details: Mapping[str, Any],
    ) -> tuple[str, LLMUsageStats]:
        import httpx

        start_time = time.time()
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        request_body = {
            "model": self.model_summary,
            "messages": [
                {
                    "role": "system",
                    "content": "Summarize the execution step concisely for trading audit logs (1-2 sentences in Russian).",
                },
                {
                    "role": "user",
                    "content": f"Step: {step_name}\nDetails: {json.dumps(dict(details), default=str)}",
                },
            ],
            "store": self.store,
            "temperature": 0.3,
        }

        async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
            try:
                response = await client.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers=headers,
                    json=request_body,
                )
                response.raise_for_status()
                data = response.json()
            except Exception as exc:
                logger.warning("openai_summary_fallback", error=str(exc))
                return f"Шаг {step_name} завершён. Статус: {details.get('status', 'OK')}", LLMUsageStats(provider="fallback")

        latency_ms = int((time.time() - start_time) * 1000)
        summary_text = data["choices"][0]["message"]["content"].strip()
        usage = data.get("usage", {})
        prompt_tokens = usage.get("prompt_tokens", 0)
        completion_tokens = usage.get("completion_tokens", 0)
        cost = self._compute_cost(prompt_tokens, completion_tokens, self.model_summary)

        stats = LLMUsageStats(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
            estimated_cost_usd=cost,
            latency_ms=latency_ms,
            provider="openai",
            model=self.model_summary,
        )
        return summary_text, stats


def get_llm_provider(
    provider_name: str | None = None,
    api_key: str | None = None,
    model_research: str | None = None,
    model_summary: str | None = None,
) -> LLMProvider:
    """Factory to instantiate the configured LLM provider."""
    from polyflip.config import settings

    provider = (provider_name or settings.AI_LAB_LLM_PROVIDER or "mock").lower()
    key = api_key or getattr(settings, "OPENAI_API_KEY", "")

    if provider == "openai" and key:
        return OpenAIResponsesProvider(
            api_key=key,
            model_research=model_research or getattr(settings, "AI_LAB_MODEL_RESEARCH", "gpt-4o"),
            model_summary=model_summary or getattr(settings, "AI_LAB_MODEL_SUMMARY", "gpt-4o-mini"),
            store=getattr(settings, "AI_LAB_LLM_STORE", False),
        )
    return MockLLMProvider(model_name=model_research or "mock-gpt-5")
